import Head from 'next/head'
import { About, Contact, Hero, Navbar, Projects, ProjectsDummy, Skills } from '../components';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Pavan Kumar Kandapagari | AI Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Skills />
      {/* <Projects /> */}
      <ProjectsDummy />
      <Contact />
    </div>
  )
}
